POST http://localhost:8080/urls/shorten
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGM0YmIyMDljOWMzNzFmZDA1MjAzYjQiLCJleHAiOjE3NTc4MTUzNzIsImlhdCI6MTc1NzcyODk3Mn0.WxGxtZVxpRVeUNW3GpkaPufnYi0Coq-ovOgWIrcnO8c

{
  "url": "https://google.com"
}

###

GET http://localhost:8080/urls/xMrqeiCNR

###

GET http://localhost:8080/urls/xMrqeiCNR/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGM0YmIyMDljOWMzNzFmZDA1MjAzYjQiLCJleHAiOjE3NTc4MTUzNzIsImlhdCI6MTc1NzcyODk3Mn0.WxGxtZVxpRVeUNW3GpkaPufnYi0Coq-ovOgWIrcnO8c

