POST http://localhost:8080/urls/shorten
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc2MzE5NzMsInVzZXJfaWQiOiI2OGMxYzY3ZGJiNzAwNjQ0ODJiMzFhMTEifQ.h7akxaFwWaLdgrsPYJ8h0NzkMcKVajbNjircPyvJIoU

{
  "url": "https://google.com"
}

###

GET http://localhost:8080/urls/r75cyCrHR
