POST http://localhost:8080/urls/shorten
Content-Type: 'application/json'
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc4MDk4MjcsInVzZXJfaWQiOiI2OGM0YmIyMDljOWMzNzFmZDA1MjAzYjQifQ.-9xSwW-LATJLGv69OMkMGB1ytbs417pFjNUpNRkxb70

{
  "url": "https://google.com"
}

###

GET http://localhost:8080/urls/xMrqeiCNR
