POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Maria",
  "password": "12345678",
  "email": "maria@gmail.com"
}

###

POST http://localhost:8080/users/signin
Content-Type: application/json

{
  "password": "12345678",
  "email": "maria@gmail.com"
}

